[main]
file_path = "../private/Default.xex"
out_directory_path = "../ppc"
switch_table_file_path = "Minecraft_switch_tables.toml"

restgprlr_14_address = 0x82151D00
savegprlr_14_address = 0x82151CB0
restfpr_14_address = 0x82152C0C
savefpr_14_address = 0x82152BC0
restvmx_14_address = 0x82154B88
savevmx_14_address = 0x821548F0
restvmx_64_address = 0x82154C1C
savevmx_64_address = 0x82154984

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false
